# Generated by Django 3.2.6 on 2021-08-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='title',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
