# Generated by Django 3.2.6 on 2021-08-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_fileupload_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
