# Generated by Django 3.2.6 on 2021-08-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_fileupload_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_image',
            field=models.ImageField(default=1, upload_to='blog/images/'),
            preserve_default=False,
        ),
    ]
