# Generated by Django 3.2.6 on 2021-08-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210809_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('faceId', models.AutoField(primary_key=True, serialize=False)),
                ('faceImg', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
