# Generated by Django 3.2.6 on 2021-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210809_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('img', models.FileField(blank=True, null=True, upload_to='blog/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='FaceImage',
        ),
    ]
