# Generated by Django 3.2.6 on 2021-08-12 13:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_imageupload_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='title',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='blog/images'),
        ),
    ]
